### ISSUE TITLE
Misaligned Umenu

### ISSUE THREAD

**Issue by Null-Senpai** [divinae/umenu#2]
Sorry, really not sure what else to call the issue. I added a picture to show what umenu looks like for me.
This is with grid size "big". "Medium" does the same. "Small  is kind of better, but there is still a weird gap at the bottom. 
First Pic is "big"
![aaaa](https://user-images.githubusercontent.com/13616397/42182639-d2533ace-7e36-11e8-811b-595f80b80a2c.png)
Second Pic is "small"
![abbbb](https://user-images.githubusercontent.com/13616397/42182740-27dd895e-7e37-11e8-84f5-7599a0ae9e13.png)

If it helps, I am using Antergos (Arch based) Linux w. Kernel 4.14.52-1-lts.
KDE Plasma 5.13.2
I have my panel at the top, and a dock (latte dock) at the bottom. Display resolution is 1366x768.

**Comment by divinae** [comment]
set small, and logout and login to Plasma :)

**Comment by Null-Senpai** [comment]
Weird, that fixed it :grinning: 
Thanks

**Comment by divinae** [comment]
It should works without that, but i have no time to investigate that :/

**Comment by Null-Senpai** [comment]
I mean, having to relog on first install is not the end of the world to be honest. It works pretty well otherwise.

**Comment by divinae** [comment]
It's linux world :D
