### ISSUE TITLE
Not looking as intended

### ISSUE THREAD

**Issue by VandaLHJ** [divinae/umenu#4]
![screenshot_20180714_001404](https://user-images.githubusercontent.com/28790923/42716257-f2ccdaae-86fa-11e8-85ba-ac78f3e48c40.png)

Well, picture is worth a thousand words. On other occasions it looks like this:
(1366x786 screen)
![screenshot_20180714_001907](https://user-images.githubusercontent.com/28790923/42716392-8ae03f52-86fb-11e8-9f04-10cd52275e78.png)

**Comment by divinae** [comment]
It is using plasma theme - get some theme with transparency :)
